name = "Dice"
uuid = "94eeadfc-1ba6-40b7-9ed8-dee71557d525"
authors = ["Guy Van den Broeck <guyvdb@gmail.com>"]
version = "0.1.0"

[deps]
CUDD = "345a2cc7-28d8-58b2-abdf-cff77ea7d7f1"
DirectedAcyclicGraphs = "1e6dae5e-d6e2-422d-9af3-452e7a3785ee"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
CUDD = "0.2.2"
DirectedAcyclicGraphs = "0.1.1"
julia = "1.6"
